/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schemas {
  configuration?: {
    /**
     * Allowed origins for a token `iss` field
     *
     * @minItems 1
     */
    allowed_issuers?: [string, ...string[]];
    /**
     * @minItems 1
     */
    acceptable_audience?: [string, ...string[]];
    /**
     * Force identities to be explicitly created or incept before being used in authentication
     */
    explicit_identity_creation?: boolean;
    /**
     * The value of `sub` of an identity token that will be assigned the `system` Role
     */
    principal?: string;
  };
  entity?: {
    /**
     * The issuer, or signer, of the token, URI like `https://accounts.google.com`
     */
    iss: string;
    /**
     * the ID that represents the principal making the request
     */
    sub: string;
  };
}
