import type { Declaration } from './providers/index.js';
import type { Schema } from '@toa.io/schemas';
import type { Annotation } from './Annotation.js';
export declare const annotation: Schema<Annotation>;
export declare const s3: Schema<Declaration>;
export declare const spaces: Schema<Declaration>;
export declare const cloudinary: Schema<Declaration>;
export declare const fs: Schema<Declaration>;
export declare const tmp: Schema<Declaration>;
export declare const test: Schema<Declaration>;
