// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "native": "English",
    "locale": "en-US",
    "dir": "ltr",
    "nav": {
      "identity": "Copy your account id",
      "markdown": "Download as Markdown",
      "mcp": "Copy the MCP address",
      "configuration": "Open Configuration",
      "introspection": "Open Introspection",
      "signin": "Sign in",
      "signout": "Sign out",
      "filter": "Filter resources",
      "back": "Back"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["en-US"];

