/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configuration {
  trust?: TrustConfiguration[];
  /**
   * Force identities to be explicitly created or incept before being used in authentication
   */
  explicit_identity_creation?: boolean;
  /**
   * The value of `sub` of an identity token that will be assigned the `system` Role
   */
  principal?: {
    iss: string;
    sub: string;
  };
}
export interface TrustConfiguration {
  /**
   * Allowed origins for a token `iss` field
   */
  iss: string;
  /**
   * Acceptable `aud` value(s)
   *
   * @minItems 1
   */
  aud?: [string, ...string[]];
  /**
   * Symmetric encryption secrets
   */
  secrets?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^HS\d{3}$".
     */
    [k: string]: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^\w+$".
       */
      [k: string]: string;
    };
  };
}
