/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Entity {
  /**
   * The authority token is valid for
   */
  authority: string;
  /**
   * The issuer, or signer, of the token, URI like `https://accounts.google.com`
   */
  iss: string;
  /**
   * The ID that represents the principal making the request
   */
  sub: string;
  id: string;
  _version?: number;
  _created?: number;
  _updated?: number;
  _deleted?: number;
}
