FROM node:alpine

RUN npm set registry {{registry}}
RUN npm set proxy {{proxy}}
RUN npm i -g @toa.io/runtime@{{version}} --production --ignore-scripts

WORKDIR /composition
ADD . .

CMD toa compose *
