// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('$lib/intl').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "resources": {
      "empty": "Nothing is served here yet.",
      "nomatch": "No results match the filter."
    },
    "resource": {
      "route": "route",
      "query": "query",
      "input": "input",
      "output": "output",
      "errors": "errors",
      "none": "none",
      "copy": "Copy JSON Schema",
      "json": "Copy the answer",
      "unset": "not defined",
      "expand": "Show what it serves",
      "mcp": "Published as a tool",
      "selection": "selection",
      "search": "Takes a text search"
    },
    "guard": {
      "public": "Anyone may reach it",
      "private": "Your own",
      "protected": "Takes a role",
      "system": "What the application runs on",
      "authenticated": "Takes being someone"
    },
    "space": {
      "user": "Userspace",
      "system": "System"
    },
    "call": {
      "open": "Call this method",
      "send": "Send request",
      "cancel": "Cancel",
      "close": "Close",
      "back": "Back",
      "hold": "Hold to send",
      "sending": "Sending…",
      "nothing": "This call takes nothing.",
      "invalid": "The body is not JSON.",
      "required": "The path does not resolve without it.",
      "answered": "answered",
      "refused": "refused",
      "body": "body",
      "empty": "No content.",
      "file": "file",
      "anything": "anything",
      "stream": "streamed",
      "streamed": "The reply arrives in parts as the work is done."
    },
    "guide": {
      "authentication": {
        "title": "Authentication"
      },
      "multipart": {
        "title": "Multipart responses"
      },
      "queries": {
        "title": "Collection queries"
      }
    }
  }
};
