// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('$lib/intl').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "values": {
      "empty": "No component declares configuration.",
      "nomatch": "No results match the filter."
    },
    "value": {
      "none": "This component has no configuration.",
      "secret": "Secret",
      "count": (count) => {
      const forms = {"one":"{n} value","other":"{n} values"};
      const locale = "en-US"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(locale);
      const rule = pluralRules.select(count);
      const table = /** @type {Record<string, string>} */ (forms);

      return (table[rule] ?? table.other).replace(/{n}/g, new Intl.NumberFormat(locale).format(count));
    },
      "epoch": "epoch",
      "title": "Configuration"
    },
    "create": {
      "action": "New",
      "title": "New configuration",
      "description": "A configuration is never changed. Creating one replaces the whole of it, so what is left out here is left out of the component.",
      "editor": "Configuration",
      "submit": "Create",
      "cancel": "Cancel",
      "malformed": "This is not valid YAML.",
      "failed": "The configuration could not be created."
    },
    "space": {
      "user": "Userspace",
      "system": "System"
    }
  }
};
