// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "native": "English",
    "locale": "en-US",
    "dir": "ltr",
    "nav": {
      "list": "List",
      "map": "Map",
      "signout": "Sign out",
      "filter": "Filter components",
      "halt": "HALT"
    },
    "halt": {
      "title": "Suspend operations",
      "description": "All systems will be inoperative for the interval you give, then resume automatically.",
      "interval": "Seconds",
      "cancel": "Cancel",
      "hold": "Hold to halt",
      "bounds": "Up to an hour"
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["en-US"];

