// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('./types').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "native": "English",
    "locale": "en-US",
    "dir": "ltr",
    "nav": {
      "list": "List",
      "map": "Map",
      "signout": "Sign out",
      "filter": "Filter components",
      "halt": "HALT"
    },
    "halt": {
      "title": "Suspend operations",
      "description": "All systems will be inoperative for the interval you give, then resume automatically.",
      "interval": "Duration",
      "cancel": "Cancel",
      "hold": "Hold to halt",
      "bounds": (min, max) => `${min}–${max} s`,
      "quiescence": "Quiescence",
      "unknown": "What a halt may ask for is not known yet.",
      "counting": "Halting when this reaches zero. Cancel to call it off.",
      "failed": "The halt was not accepted. Try again."
    }
  }
};

/** @type {import('./types').Locale[]} */
export const locales = ["en-US"];

