# This file helps with IDE autocompletion
compositions:
  - name: todos
    image: localhost:5000/composition-todos:0.0.0
    replicas: 2
    mounts:
      - name: mount-name
        path: /storage
        claim: storage-pvc
    components:
      - todos-tasks
      - todos-stats
    variables:
      - name: TOA_CONFIGURATION_TODOS_TASKS
        value: foo
        secret:
          name: secret-name
          key: secret-key
          optional: false
  - name: users
    image: localhost:5000/composition-users:0.0.0
    replicas: 3
    components:
      - users-users
components:
  - todos-tasks
  - todos-stats
  - users-users
services:
  - name: resources-gateway
    image: localhost:5000/resources-gateway:0.0.0
    port: 8000
    replicas: 2
    ingress:
      default: true
      hosts: [dummies.toa.io]
      class: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    variables:
      - name: TOA_CONFIGURATION_TODOS_TASKS
        value: foo
        secret:
          name: secret-name
          key: secret-key
    probe:
      port: 8000
      path: /.ready
      delay: 1

proxies:
  - name: storage-proxy
    target: host.docker.internal
environment: development
credentials: docker-credentials
