// Auto-generated by i18n CLI - do not edit manually

/** @type {Record<import('$lib/intl').Locale, import('./types').Dictionary>} */
export const dictionaries = {
  "en-US": {
    "nodes": {
      "empty": "No components have reported yet.",
      "nomatch": "No results match the filter."
    },
    "node": {
      "operations": (count) => {
      const forms = {"one":"{n} operation","other":"{n} operations"};
      const locale = "en-US"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(locale);
      const rule = pluralRules.select(count);
      const table = /** @type {Record<string, string>} */ (forms);

      return (table[rule] ?? table.other).replace(/{n}/g, new Intl.NumberFormat(locale).format(count));
    },
      "events": (count) => {
      const forms = {"one":"{n} event","other":"{n} events"};
      const locale = "en-US"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(locale);
      const rule = pluralRules.select(count);
      const table = /** @type {Record<string, string>} */ (forms);

      return (table[rule] ?? table.other).replace(/{n}/g, new Intl.NumberFormat(locale).format(count));
    },
      "receivers": (count) => {
      const forms = {"one":"{n} receiver","other":"{n} receivers"};
      const locale = "en-US"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(locale);
      const rule = pluralRules.select(count);
      const table = /** @type {Record<string, string>} */ (forms);

      return (table[rule] ?? table.other).replace(/{n}/g, new Intl.NumberFormat(locale).format(count));
    },
      "state": "state",
      "stateless": "stateless",
      "extensions": (count) => {
      const forms = {"one":"{n} extension","other":"{n} extensions"};
      const locale = "en-US"; // This will be replaced by the build system
      const pluralRules = new Intl.PluralRules(locale);
      const rule = pluralRules.select(count);
      const table = /** @type {Record<string, string>} */ (forms);

      return (table[rule] ?? table.other).replace(/{n}/g, new Intl.NumberFormat(locale).format(count));
    },
      "schema": "schema",
      "input": "input",
      "output": "output",
      "errors": "errors",
      "storage": "storage",
      "associated": "associated",
      "version": "version",
      "binding": "binding",
      "conditioned": "conditioned",
      "adaptive": "adaptive",
      "none": "none"
    },
    "map": {
      "empty": "The map has no connections yet."
    }
  }
};
